Readme is ready
mystuding123/Studying pull request #3
Opened 2019-12-03 16:40 UTC by lolissimo2402

2019-12-03 18:02 UTC, vsvyst requested changes
Did you verify the output of readmy document? It does not look like expcted.
Please browse the Internet and make more readable document. here is an example https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

2019-12-04 21:49 UTC, closed without merging

2019-12-04 22:24 UTC, lolissimo2402 commented
Здоров Вова..Рідмі файл вроді залив..все перешарив ну якшо я все правільно
зрозумів то якось так якшо не так то я щось не правильно зрозумів))
З тасками проблемка..я в чаптер 3 таск 1 залив солюшн і я не можу виидалити
бренчу шоб не пропав солюшн..короче я запутався з тим всім..

вт, 3 дек. 2019 г. в 20:02, vsvyst <notifications@github.com>:

> *@vsvyst* requested changes on this pull request.
>
> Did you verify the output of readmy document? It does not look like
> expcted.
> Please browse the Internet and make more readable document. here is an
> example https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mystuding123/Studying/pull/3?email_source=notifications&email_token=AMKTS2HZEKE7WD7L7FJFUFTQW2NJXA5CNFSM4JU3BRFKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCNZY5KA#pullrequestreview-326340264>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKTS2F4FWJ7KEUJJKNPCP3QW2NJXANCNFSM4JU3BRFA>
> .
>

2019-12-04 22:27 UTC, lolissimo2402 commented
тепер получається що я створюю бренчу і заливаю туда все що є.. а маю
залити тільки 2 файлики...короче з тим треба якось розібратися...хоча зараз
ще попробую

чт, 5 дек. 2019 г. в 00:24, lolik lolik <lolissimo2402@gmail.com>:

> Здоров Вова..Рідмі файл вроді залив..все перешарив ну якшо я все правільно
> зрозумів то якось так якшо не так то я щось не правильно зрозумів))
> З тасками проблемка..я в чаптер 3 таск 1 залив солюшн і я не можу
> виидалити бренчу шоб не пропав солюшн..короче я запутався з тим всім..
>
> вт, 3 дек. 2019 г. в 20:02, vsvyst <notifications@github.com>:
>
>> *@vsvyst* requested changes on this pull request.
>>
>> Did you verify the output of readmy document? It does not look like
>> expcted.
>> Please browse the Internet and make more readable document. here is an
>> example https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mystuding123/Studying/pull/3?email_source=notifications&email_token=AMKTS2HZEKE7WD7L7FJFUFTQW2NJXA5CNFSM4JU3BRFKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCNZY5KA#pullrequestreview-326340264>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AMKTS2F4FWJ7KEUJJKNPCP3QW2NJXANCNFSM4JU3BRFA>
>> .
>>
>

2019-12-04 22:28 UTC, lolissimo2402 commented
залию 3 завдання скажеш ти так добре

чт, 5 дек. 2019 г. в 00:27, lolik lolik <lolissimo2402@gmail.com>:

> тепер получається що я створюю бренчу і заливаю туда все що є.. а маю
> залити тільки 2 файлики...короче з тим треба якось розібратися...хоча зараз
> ще попробую
>
> чт, 5 дек. 2019 г. в 00:24, lolik lolik <lolissimo2402@gmail.com>:
>
>> Здоров Вова..Рідмі файл вроді залив..все перешарив ну якшо я все
>> правільно зрозумів то якось так якшо не так то я щось не правильно
>> зрозумів))
>> З тасками проблемка..я в чаптер 3 таск 1 залив солюшн і я не можу
>> виидалити бренчу шоб не пропав солюшн..короче я запутався з тим всім..
>>
>> вт, 3 дек. 2019 г. в 20:02, vsvyst <notifications@github.com>:
>>
>>> *@vsvyst* requested changes on this pull request.
>>>
>>> Did you verify the output of readmy document? It does not look like
>>> expcted.
>>> Please browse the Internet and make more readable document. here is an
>>> example https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/mystuding123/Studying/pull/3?email_source=notifications&email_token=AMKTS2HZEKE7WD7L7FJFUFTQW2NJXA5CNFSM4JU3BRFKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCNZY5KA#pullrequestreview-326340264>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AMKTS2F4FWJ7KEUJJKNPCP3QW2NJXANCNFSM4JU3BRFA>
>>> .
>>>
>>

2019-12-05 10:58 UTC, lolissimo2402 commented
чт, 5 дек. 2019 г. в 00:27, lolik lolik <lolissimo2402@gmail.com>:

> залию 3 завдання скажеш ти так добре
>
> чт, 5 дек. 2019 г. в 00:27, lolik lolik <lolissimo2402@gmail.com>:
>
>> тепер получається що я створюю бренчу і заливаю туда все що є.. а маю
>> залити тільки 2 файлики...короче з тим треба якось розібратися...хоча зараз
>> ще попробую
>>
>> чт, 5 дек. 2019 г. в 00:24, lolik lolik <lolissimo2402@gmail.com>:
>>
>>> Здоров Вова..Рідмі файл вроді залив..все перешарив ну якшо я все
>>> правільно зрозумів то якось так якшо не так то я щось не правильно
>>> зрозумів))
>>> З тасками проблемка..я в чаптер 3 таск 1 залив солюшн і я не можу
>>> виидалити бренчу шоб не пропав солюшн..короче я запутався з тим всім..
>>>
>>> вт, 3 дек. 2019 г. в 20:02, vsvyst <notifications@github.com>:
>>>
>>>> *@vsvyst* requested changes on this pull request.
>>>>
>>>> Did you verify the output of readmy document? It does not look like
>>>> expcted.
>>>> Please browse the Internet and make more readable document. here is an
>>>> example https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/mystuding123/Studying/pull/3?email_source=notifications&email_token=AMKTS2HZEKE7WD7L7FJFUFTQW2NJXA5CNFSM4JU3BRFKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCNZY5KA#pullrequestreview-326340264>,
>>>> or unsubscribe
>>>> <https://github.com/notifications/unsubscribe-auth/AMKTS2F4FWJ7KEUJJKNPCP3QW2NJXANCNFSM4JU3BRFA>
>>>> .
>>>>
>>>